/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all buildings */
        get: operations["BuildingsController_findAll"];
        put?: never;
        /** Create a new building */
        post: operations["BuildingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a building by id */
        get: operations["BuildingsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a building by id */
        delete: operations["BuildingsController_remove"];
        options?: never;
        head?: never;
        /** Update a building by id */
        patch: operations["BuildingsController_update"];
        trace?: never;
    };
    "/api/v1/buildings/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Restore a deleted building */
        patch: operations["BuildingsController_restore"];
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login user */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/check-auth-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_checkAuthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SeedController_seedDB"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateBuildingDto: {
            /**
             * @description Building name
             * @example Main Building
             */
            name: string;
            /**
             * @description Building description
             * @example New building in the city
             */
            description?: string;
            /**
             * @description Year built
             * @example 2020
             */
            yearBuilt: number;
            /**
             * @description Property type
             * @example RESIDENTIAL
             * @enum {string}
             */
            propertyType: "RESIDENTIAL" | "COMMERCIAL" | "MIXED";
            /**
             * @description Building address
             * @example Main Street
             */
            address: string;
            /**
             * @description Building district
             * @example Main District
             */
            district: string;
            /**
             * @description Building city
             * @example Main City
             */
            city: string;
            /**
             * @description Building province
             * @example Main Province
             */
            province: string;
            /**
             * @description Building postal code
             * @example 15001
             */
            postalCode?: string;
            /**
             * @description Number of floors
             * @example 10
             */
            floors: number;
            /**
             * @description Building phone number
             * @example +51 987 654 321
             */
            phoneNumber?: string;
            /**
             * @description Building email
             * @example contact@building.com
             */
            email?: string;
            /**
             * @description Building amenities
             * @example [
             *       "ELEVATOR",
             *       "PARKING"
             *     ]
             */
            amenities: ("PARKING" | "SECURITY_24_7" | "ELEVATOR" | "WHEELCHAIR_ACCESS" | "WHEELCHAIR_LIFT" | "FIRE_ALARM" | "CAMERAS")[];
        };
        Building: Record<string, never>;
        UpdateBuildingDto: {
            /**
             * @description Building name
             * @example Main Building
             */
            name?: string;
            /**
             * @description Building description
             * @example New building in the city
             */
            description?: string;
            /**
             * @description Year built
             * @example 2020
             */
            yearBuilt?: number;
            /**
             * @description Property type
             * @example RESIDENTIAL
             * @enum {string}
             */
            propertyType?: "RESIDENTIAL" | "COMMERCIAL" | "MIXED";
            /**
             * @description Building address
             * @example Main Street
             */
            address?: string;
            /**
             * @description Building district
             * @example Main District
             */
            district?: string;
            /**
             * @description Building city
             * @example Main City
             */
            city?: string;
            /**
             * @description Building province
             * @example Main Province
             */
            province?: string;
            /**
             * @description Building postal code
             * @example 15001
             */
            postalCode?: string;
            /**
             * @description Number of floors
             * @example 10
             */
            floors?: number;
            /**
             * @description Building phone number
             * @example +51 987 654 321
             */
            phoneNumber?: string;
            /**
             * @description Building email
             * @example contact@building.com
             */
            email?: string;
            /**
             * @description Building amenities
             * @example [
             *       "ELEVATOR",
             *       "PARKING"
             *     ]
             */
            amenities?: ("PARKING" | "SECURITY_24_7" | "ELEVATOR" | "WHEELCHAIR_ACCESS" | "WHEELCHAIR_LIFT" | "FIRE_ALARM" | "CAMERAS")[];
        };
        RegisterUserDto: {
            /**
             * @description User first name
             * @example John Doe
             */
            firstName: string;
            /**
             * @description User last name
             * @example Doe
             */
            lastName: string;
            /**
             * @description User email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description User password
             * @example password
             */
            password: string;
        };
        AuthResponse: {
            /**
             * @description User ID
             * @example 1
             */
            id: number;
            /**
             * @description User first name
             * @example John
             */
            firstName: string;
            /**
             * @description User last name
             * @example Doe
             */
            lastName: string;
            /**
             * @description User email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description JWT access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
        };
        LoginUserDto: {
            /**
             * @description User email
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description User password
             * @example password
             */
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    BuildingsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The buildings has been successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BuildingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBuildingDto"];
            };
        };
        responses: {
            /** @description The building has been successfully created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BuildingsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The building has been successfully retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description building not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BuildingsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The building has been successfully deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BuildingsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBuildingDto"];
            };
        };
        responses: {
            /** @description The building has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description building not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BuildingsController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The building has been successfully updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Building"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description building not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserDto"];
            };
        };
        responses: {
            /** @description User successfully registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserDto"];
            };
        };
        responses: {
            /** @description User successfully logged in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    AuthController_checkAuthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SeedController_seedDB: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
