// This file was auto-generated by prisma-generator-typescript-interfaces

export type UnitType = 'APARTMENT' | 'OFFICE' | 'COMMERCIAL'

export type UnitStatus = 'AVAILABLE' | 'OCCUPIED' | 'MAINTENANCE'

export type EmployeeRole =
  | 'MANAGER'
  | 'SECURITY'
  | 'CLEANER'
  | 'MAINTENANCE'
  | 'GARDENER'
  | 'RECEPTIONIST'

export type PropertyType = 'RESIDENTIAL' | 'COMMERCIAL' | 'MIXED'

export type UserRole = 'ADMIN' | 'MANAGER' | 'RESIDENT' | 'STAFF'

export type Building = {
  id: number
  name: string
  description: string | null
  yearBuilt: number
  propertyType: PropertyType
  address: string
  district: string
  city: string
  province: string
  postalCode: string | null
  floors: number
  phoneNumber: string | null
  email: string | null
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  manager?: Employee
  managerId: number
}

export type Employee = {
  id: number
  buildings?: Building[]
  firstName: string
  lastName: string
  phoneNumber: string | null
  email: string
  role: EmployeeRole
  createdAt: Date
  updatedAt: Date
  startDate: Date
  endDate: Date | null
  isActive: boolean
}

export type Unit = {
  id: number
  buildingId: number
  number: string
  floor: number
  type: UnitType
  status: UnitStatus
  createdAt: Date
  updatedAt: Date
}

export type CommonArea = {
  id: number
  buildingId: number
  name: string
  description: string | null
  capacity: number
  isActive: boolean
  createdAt: Date
  updatedAt: Date
}
